# Generated by Django 5.2.6 on 2025-10-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'centros_medicos',
            },
        ),
        migrations.CreateModel(
            name='ContenidoInformativo',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contenidos_informativos',
            },
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id_fundacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fundacion', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'fundaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('id_centro', models.ForeignKey(db_column='id_centro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EsclerosisApp.centromedico')),
            ],
            options={
                'db_table': 'medicos',
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id_testimonio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='EsclerosisApp.usuario')),
            ],
            options={
                'db_table': 'testimonios',
            },
        ),
    ]
