# Generated by Django 5.2.6 on 2025-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonioVerificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=12)),
                ('mostrar_nombre', models.BooleanField(default=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'testimonios_verificados',
            },
        ),
    ]
