# Generated by Django 5.2.6 on 2025-10-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0002_testimonioverificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonioverificado',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonioverificado',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
