# Generated by Django 5.2.6 on 2025-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0006_mensajecontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={},
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
