# Generated by Django 5.2.6 on 2025-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0008_fundacionpropuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacionpropuesta',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundacionpropuesta',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
