# Generated by Django 5.2.6 on 2025-11-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0009_fundacionpropuesta_lat_fundacionpropuesta_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacionpropuesta',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundacionpropuesta',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundacionpropuesta',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundacionpropuesta',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundacionpropuesta',
            name='ubicacion',
            field=models.CharField(max_length=250),
        ),
    ]
