# Generated by Django 5.2.6 on 2025-11-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0010_fundacionpropuesta_tiktok_fundacionpropuesta_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacionpropuesta',
            name='ubicacion',
            field=models.CharField(max_length=150),
        ),
    ]
