# Generated by Django 5.2.6 on 2025-11-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EsclerosisApp', '0011_alter_fundacionpropuesta_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundacionpropuesta',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='fundacionpropuesta',
            name='lng',
        ),
    ]
